[project]
name = "miditohandpanscore"
version = "0.1.0"
description = "MIDI to Handpan LilyPond score converter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mido>=1.3.3",
]

[project.scripts]
handpan-generate-scales = "miditohandpanscore.generate_scales:main"
handpan-midi-to-score = "miditohandpanscore.midi_to_score:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/miditohandpanscore"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]
